export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const PASSWORD_RECOVER_EMAIL = "PASSWORD_RECOVER_EMAIL";
export const PASSWORD_RECOVER_CODE = "PASSWORD_RECOVER_CODE";

export const ADMIN_CURRENT_USER = "ADMIN_CURRENT_USER";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_SINGLE_USER = "GET_SINGLE_USER";

export const GET_REGISTERED_VEHICLE = "GET_REGISTERED_VEHICLE";
export const GET_VEHICLE = "GET_VEHICLE";

export const GET_JOBS = "GET_JOBS";
export const GET_JOB = "GET_JOB";

export const GET_FEEDBACKS = "GET_FEEDBACKS";
export const GET_FEEDBACK = "GET_FEEDBACK";

export const GET_SETTING = "GET_SETTING";
